# Generated by Django 5.1.1 on 2026-02-24 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(max_length=50, unique=True, verbose_name='Number Plate')),
                ('vehicle_name', models.TextField(blank=True, max_length=25, null=True, verbose_name='Name of vehicle')),
                ('contact_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Rider',
                'verbose_name_plural': 'Delivery Riders',
            },
        ),
    ]
